services:
  app:
    container_name: ${PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/eastzoo/Project/files/${PROJECT_NAME}/uploads:/usr/src/app/uploads
      - /home/eastzoo/Project/files/${PROJECT_NAME}/files:/usr/src/app/files
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped  # 서버 재시작 시 자동 실행
    # depends_on:
    #   - redis

  # Redis 서비스 추가 - 토큰 관리용
  # redis:
  #   image: redis:7-alpine
  #   container_name: ${PROJECT_NAME}-redis
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - /home/redis:/data
  #   command: redis-server --appendonly yes
